### ISSUE TITLE
Merging informations

### ISSUE THREAD

**Issue by Leerzeichen** [autowp/autowp.github.io#1]
I'm also on the way reverse engineering the protocol over CAN from my Peugeot 407...
I forked your branch and added my first investigations (more will come the next days)

Would be nice if we can exchange information.

Best regards from Germany

**Comment by autowp** [comment]
Great. Sure thats nice.

I will translate the rest to the english soon.

**Comment by autowp** [comment]
Merged your data and little format it, but 0x0B6 have some issues with extra bits in RPM. Can you clear that?

**Comment by Leerzeichen** [comment]
Sure? In my logged data, the first two bytes right shifted 3 times 
give the exact rpm. Same is in 13E second and third Byte...

**Comment by Leerzeichen** [comment]
Main things what I'm searching at the moment is the actual climate setting and what audio source is selected... If I get this informations, the original display will leave and my android tablet is moving in...
Debugging will not stop, but then all data will be collected, not only special sessions ;)

**Comment by autowp** [comment]
Heh. Thats not all important things to remove display. What about 0x1A1 (Info messages)?

0B6: You wrote this
MMMM MMM - 7 bits
000 - 3 bits
SSSS SSSS - 8 bits
10010110 00000011 10010011 11010000 - 24 bits

only 42 bits of 64 total

**Comment by Leerzeichen** [comment]
Argh...
Okay....
MMMMMMMM MMMMM000 SSSSSSSS SSSSSSSS  of course...
Next two bytes are a counter (incrementing only when driving) following by a one byte counter and an unknown byte

Sample 
40 28 10 AB 90 34 16 D0                    => 2053 rpm 42,67 km/h
4E 00 22 CF 76 23 F3 D0                    => 2496 rpm 89,11 km/h

The original display will move to the glove compartment at first ;) But for the daily use, not much more is needed

**Comment by autowp** [comment]
Done in https://github.com/autowp/autowp.github.io/commit/8ff0af0ce4b1c35f1e343a33387dfca53cdabdd0
Thanks.

In my car display moved to japan version place like  [here](http://forum.aves-peugeot.ru/gallery/albums/userpics/11102/IMG_3437_resize.JPG)
